### ISSUE TITLE
Cannot download existing GDAP relationships

### ISSUE THREAD

**Issue by neo475269** [microsoft/PartnerCenter-GDAPTransition#21] opened 2022-09-16 06:53 UTC
Starting from today, I failed to download GDAP relationships.  I tried on 2 computers with different network connections and still failed.  The error message is "[0: Error] PartnerLed.Providers.GdapProvider - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10.0.1.6:20006)"

Anyone sharing similar experience?

**Comment by mopkick** [comment] 2022-09-16 12:11
Yes we cannot handle too
- Download GDAP Relationships (5)  
- Download Security Group (4) "[0: Error] PartnerLed.Providers.AccessAssignmentProvider - Unexpected character encountered while parsing value: ▼. Path '', line 0, position 0."
-  Process Create Security Group-Role Assignment(s) (9): no failure but not action


This procedure was carried out as a test 2 weeks ago and was successful. I don´t know?!

**Comment by sansbacher** [comment] 2022-09-16 17:24
It works for me - running: 5. Download existing GDAP relationship(s). In fact all of them work (options 1, 3, 4, 5, 8, and10)  
But I just noticed this thread in the MS Partner Community where someone is complaining about the [APIs that back this GDAP stuff returning an HTTP 500](https://www.microsoftpartnercommunity.com/t5/Secure-Application-Model/GDAP-beta-tenantRelationships-endpoint-returns-500-internal/m-p/76309/highlight/true#M287). Janosch suggested it was likely a technical issue. 

Perhaps it is - or was - related? And maybe it's fixed now? **Try again perhaps?**

**Comment by SampoHau** [comment] 2022-09-19 11:16
Ran into this also. I had a plan where I first would create the relationships and once I had done those I would download the relationships and run security group assignments. There are lots of GDAP Relationships in my case (2000+), so my guess the connection is timing out.

Please fix ASAP!

**Comment by manusidd** [comment] 2022-09-19 13:54
This issue has been fixed. Please verify.

**Comment by mopkick** [comment] 2022-09-20 07:24
Thanks a lot - it works after re-download the new package.
If they "9" not working you must download the "5" again an copy to the demanded path and run again. 
Happy GDAPing ;-)

**Comment by SampoHau** [comment] 2022-09-20 15:22
Yes, downloading works now. Thanks for swift action!

@mopkick, that's exactly what I did and saved myself a lot of time. :) Thanks for this superb tool!

**Comment by manusidd** [comment] 2022-09-20 15:52
The issue is fixed.

**Closed** 2022-09-20 15:52 UTC
